/* eslint-disable react/no-unescaped-entities */
/* eslint-disable max-len */
import React from 'react';
import classNames from 'classnames';

import css from '@Assets/sass/custom.sass';
import { createUseStyles } from 'react-jss';

const useStyles = createUseStyles({
  root: {
    padding: [32, 0],
  },
  list: {
    paddingLeft: 40,
    marginBottom: 24,
    listStyle: 'disc',
  },
  link: {
    color: '#85a5ff',
  },
}, {
  name: 'TermsPage',
});

const TermsPage = () => {
  const classes = useStyles();
  return (
    <div className={classNames(css.container, classes.root)}>
      <h3 className={classNames(css.title, css['is-4'])}>TOPIXIN INC. Terms of Use</h3>
      <hr />
      <p className={classNames(css.subtitle, css['is-6'])}>
        Last Updated 06/29/2020
      </p>
      <p className={classNames(css.subtitle, css['is-6'])}>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS WEBSITE. This is a legally binding agreement between you and TOPIXIN INC. These Terms of Use govern use of the websites operated by or on behalf of Topixin Inc. ("Topixin" or "we" or "us") and on which these Terms of Use appear, including those at all Topixin URLs ("Websites") and the Topixin services provided on or through the Websites and/or accessible through various desktop and mobile web browsers, locally installed mobile web applications, third party platforms including social networking sites ("Third Party Platforms"), and various API services and other services that we may offer from time to time, including without limitation social, online and/or other applications (including mobile applications), community forums, and blogs (collectively, the "Services"). Your right to use the Websites and/or Services is subject to your compliance with all of the terms and conditions set forth herein.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Your access to and use of the Websites and Services are governed by these Terms of Use ("Terms of Use") and Topixin's Privacy Policy located at <a target='_blank' href='/privacy-policy' className={classNames(classes.link)}>http://www.topixin.io/privacy-policy</a> ("Privacy Policy") which is incorporated by reference in its entirety herein (both the Terms of Use and Privacy Policy shall collectively be referred to herein as the "Terms" unless specifically stated otherwise). By accessing and/or using the Websites and/or Services you agree to abide by the Terms, including all rules, terms, conditions, restrictions and notices therein. If you do not wish to be bound by the Terms, you may not access or use the Websites or the Services.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Topixin reserves the right to, and will not be liable to any user or third party, for doing the following:</p>
      <ul className={classNames(classes.list)}>
        <li className={classNames(css.subtitle, css['is-6'])}>changing the Terms at any time;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>changing the Websites or Services, including terminating, eliminating, supplementing, modifying, adding to or discontinuing any content, functionality, promotion, data on or feature of the Websites or Services or the hours that the Websites or Services are available;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>changing any fees or charges in connection with the use of the Websites or the Services.</li>
      </ul>
      <p className={classNames(css.subtitle, css['is-6'])}>These Terms of Use were posted on 05/29/2020. Please look here for any updates, which will be posted for your review.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>1. Changes to these Terms of Use.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Topixin has included the effective date of these Terms of Use both on the first and last page of this document. Topixin reserves the right to make changes to any Terms at any time, however, Topixin shall provide notification to you in advance of any changes becoming effective, such as by posting a notification on the Websites or via email. If you continue to access and/or use the Websites or Materials (defined below), including any of the Services available through any Third Party Platform, after the effective date of such changes, then such access and/or use will be deemed an acceptance of and an agreement to follow and be bound by the Terms as changed. The revised Terms supersede all previous notices or statements regarding the Websites and Materials. For this reason, we encourage you to review these Terms any time you access or use the Websites or Materials, and recommend that you print out a copy for your records. Upon our request, you agree to sign a non-electronic version of these Terms of Use and any other policies or agreements set forth or available on or through the Websites or any Third Party Platform.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>2. Materials.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The information and materials provided on or through the Websites and/or Services, including without limitation, any other data, text, pictures, graphics, audio, video, icons, games, software, and upgrades for use on or through the Websites and/or the Services, links, and other content, features and services available on or through the Websites and/or the Services (collectively, the "Materials"), excluding Submissions (defined below), are intended to educate and inform you about us and our business and provide you with access to the Services. THE MATERIALS ARE PROVIDED "AS IS" AND YOUR USE THEREOF IS ENTIRELY AT YOUR OWN RISK.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>3. Limited License and Right to Use the Materials.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The Websites and Services are provided for your enjoyment, and unless otherwise specified on or in the Websites or Services, solely for your own personal use. Topixin hereby grants you a personal, non-exclusive, non-transferable, non-sublicensable, limited license to access and use the Websites and Services for your own non-commercial entertainment purposes, subject to your complete compliance with the Terms and any and all other terms and policies set forth on or in the Websites or Services, including without limitation on Third Party Platforms. Topixin reserves the right to revoke your right to use the Website or the Services at any time as further set forth in Section 20 herein. You acknowledge that the time that you spend on or using the Websites and/or Services including without limitation on any Third Party Platforms, is solely for your personal entertainment purposes, and that no monetary value can be attributed to such time and that, but for the license granted herein, you are not entitled under the law to use or have access to the Websites or Services and/or the Materials.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Except as expressly provided in the Terms, Topixin does not grant you any other express or implied rights or license in or to the Materials, Services and/or the Websites, and all right, title and interest that Topixin has in the Materials, Services and/or the Websites rights not explicitly granted to you by Topixin or its licensors are retained by Topixin or its licensors, respectively.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Except as expressly set forth in the Terms, you may not modify (including without limitation making derivative works), copy, adapt, reverse engineer, de-compile or otherwise reduce to human perceivable format, distribute, frame, reproduce, republish, download, scrape, display, post, transmit, transfer, license or sublicense, publicly display, or sell in any form or by any means, in whole or in part, Materials without Topixin's or its licensors' express prior written permission. To the extent you are granted express permission or allowed to do so under applicable law, you must retain all trademark, copyright and other proprietary notices on downloaded and copied Materials, and any such downloads or copies are subject to the terms and conditions of these Terms.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>4. Intellectual Property.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You acknowledge that the Materials, Services and Websites are protected by and/or embody copyrights, trademarks, patents, trade secrets and/or other proprietary rights ("Intellectual Property") owned by Topixin, and/or its licensors, including without limitation the selection, coordination, arrangement, compilation, assembly and any enhancements thereto. The Websites, Services and Materials (and any Intellectual Property and other rights relating thereto) are and will remain the property of Topixin. The trademarks, trade names, trade dress, logos, and service marks displayed on the Websites or any Third Party Platform, including the Topixin marks, logos and trade dress are the registered and/or unregistered trademarks of Topixin, Topixin's licensors and vendors and/or other third parties. You acknowledge that the Intellectual Property is valid and protected in all media existing now or later developed and under United States and foreign laws. You acknowledge that you do not acquire any ownership rights in or to the Intellectual Property.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The Intellectually Property may not be used by you for any purpose without Topixin's prior express written permission, unless permissible by law. Notwithstanding the foregoing, the Intellectual Property may not be used in connection with any product or service that is not Topixin's, in any manner that is likely to cause confusion among consumers, or in any manner that discloses confidential information or disparages Topixin. Nothing contained on the Websites or available on any Third Party Platform should be construed as granting, by implication, estoppel or otherwise, any license or right to use any Intellectual Property. Except as expressly provided in a separate license agreement, Topixin and its licensors of the Materials do not grant any express or implied rights to you under any patents, copyrights, trademarks, or trade secret information.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>5. Your Account.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>In order to access certain areas of or participate in certain activities contained on the Websites and/or the Services, we may require you to create an account ("Account").You acknowledge and agree that you have no ownership or other proprietary interest in the Account. To create an Account, we may ask or require you to provide us with certain personal information (e.g., your name and e-mail address). Providing us with your personal information is your choice. Each time you decide to provide us with your personal information, you agree to: (a) provide accurate, current and complete information about yourself as prompted by our registration form (including your current e-mail address), and (b) maintain and update your information (including your e-mail address) to keep it accurate, current and complete. You acknowledge that, if any information provided by you is untrue, inaccurate, not current or incomplete, we have the right to terminate your access to and use of the Websites and/or the Services (or any portion thereof) or your participation in any activity contained on or available through the Websites and/or any Third Party Platform.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>In order to access certain areas of, or participate in certain activities contained on the Websites and/or the Services, we may require you to select a username, topic name and/or password. You may also be able to create unique topic names to categorize content on your individualized page. Your username and/or topic name(s) are subject to certain terms and Standards, as set forth in Sections 6 and 7 below. You agree that Topixin has the right in its sole discretion to suspend or terminate your Account, any topic, refuse any and all current or future use of the Websites and/or Services (or any portion thereof).</p>
      <p className={classNames(css.subtitle, css['is-4'])}>6. Username, Topic Names and Passwords.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Topixin may refuse to grant you a username and/or topic name in its sole discretion for any reason, including if it impersonates someone else or misleadingly implies an association with the persona of another person or entity, is or may be illegal, is or may be protected by trademark or other proprietary rights law, is vulgar or otherwise offensive, or may cause confusion, or for any other reason as determined by us in our sole discretion. Your selection and use of a specific username and/or topic name does not convey any ownership or rights in that username and/or topic name and Topixin reserves the right to revoke and/or reassign any username and/or topic name in its sole discretion. You understand and agree that Topixin reserves the right to change, remove, alter or delete any username and/or topic name, with or without prior notice to you, at any time and for any reason in Topixin's sole discretion.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR USERNAME AND PASSWORD AND ALL ACCESS TO AND USE OF YOUR ACCOUNT, INCLUDING ANY AND ALL ACTIVITIES (INCLUDING USE OF THE SERVICES ON OR AVAILABLE THROUGH THE WEBSITES OR THIRD PARTY PLATFORMS, AS APPLICABLE) THAT ARE CONDUCTED THROUGH THE USE OF YOUR USERNAME AND PASSWORD WHETHER OR NOT AUTHORIZED BY YOU.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You agree not to transfer or resell your or otherwise convey your Account or the right to use your Account or any rights therein to anyone. If you have reason to believe that your Account is no longer secure, you must: (i) promptly change your password, and (ii) immediately notify us of the problem by e-mailing us at support@topixin.com (with the subject line: "Username Password Security Issues").</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You may not use anyone else's Account at any time and you may not allow anyone else to use your Account at any time. You agree that Topixin will not be liable for any loss you may incur as a result of someone else using your Account, either with or without your knowledge, and you further agree that you will be liable for losses incurred by Topixin or another party due to someone else using your Account . Because of this, Topixin strongly recommends that you exit from your Account at the end of each session.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>7. Code of Conduct.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>While using any of the Website and/or Materials, including on or in any Submissions (as defined below), postings or ratings, you agree to follow our community standards set forth below (the "Standards"), and you agree not to:</p>
      <ul className={classNames(classes.list)}>
        <li className={classNames(css.subtitle, css['is-6'])}>Create a false identity or impersonate any person, including without limitation, identities falsely indicating that you are an Topixin official or representative, message board moderator, guide, another user or host or that you are a celebrity or public figure;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Create any posts, username, topic name, or subject lines containing profanity, sexually graphic or offensive language, including any uses of characters such as \@#$% to replace letters;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Send, post, transmit or make available any content or message that is false, inaccurate, misleading, disruptive, unlawful, harmful, threatening, abusive, harassing, defamatory, pornographic, vulgar, inciteful, racist or otherwise objectionable, including any topics that may be harmful to or threaten the security of a child or minor;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Engage in rude, unlawful, harassing, vulgar, obscene, hateful, threatening, abusive, inciteful, or otherwise objectionable behavior; all such behavior may be reported to the authorities;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Suggest, illicit or encourage any illegal activity;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Submit content, materials or Submissions that are subject to intellectual property protection, including without limitation, copyright, trademark, trade secret or patent rights, or otherwise subject to third party proprietary rights, including, without limitation, privacy and publicity rights, unless you are the owner of such rights or have permission from the owner to do so and to grant Topixin all of the license rights necessary to transmit or maintain such content, material, or Submissions;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Send, post, transmit or make available any: any material, non-public information about any person or company without the express authorization to do so;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Send, post, transmit or otherwise make available  any advertisements, solicitations, chain letters, pyramid schemes, junk mail, SPAM, investment opportunities or other unsolicited or unauthorized commercial or promotional content, materials, SPAM or communication (except as otherwise expressly permitted herein or in writing by Topixin);</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Institute an attack upon any server used in connection with the Websites and/or the Services or any portion thereof or otherwise attempt to disrupt such servers, including any Services available on or through the Websites and/or any Third Party Platform;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Send, post, transmit or otherwise make available any material or Submissions regarding hacking, cracking, exploiting, or otherwise making use of the Websites or the Services;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Attempt to or actually restrict or inhibit any other user from using and enjoying the Websites and/or the Services, including without limitation, by disrupting the flow of Forums with vulgar or obscene language, abusiveness, hitting the return key repeatedly, inputting excessively large images so the screen goes by too fast to read, use of excessive SHOUTING (all capital letters) in an attempt to disturb other users, bullying, griefing, "spamming", or "flooding" (continuous posting repetitive text);</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Use any robot (bot), spider, scraper or other unauthorized or automated means to modify, use or access the Websites or the Services, or any portion thereof, or any Services available on or through any Third Party Platform;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Send, post or transmit any software or other materials that contain any viruses, worms, trojan horses, defects, date bombs, time bombs or other items of a destructive nature;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Modify, adapt, sublicense, translate, sell, reverse engineer, decompile or disassemble all or any portion of the Websites or Materials, including the Services;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>"Frame" or "mirror" any part of the Websites and/or the Services without Topixin's prior written authorization;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Attempt to obtain passwords, other Account information, or any other private information from any other user of the Website or the Services, including any Services made available on or through any Third Party Platform, and including without limitation, the collection personal information about others, such as email addresses or geo-locations;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Harvest or collect information about users of the Websites or the Services, including those made available on or through any Third Party Platform;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Buy, sell or trade any user Account for non-Topixin information or item (including cash) or vice versa;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Access another user's Account without permission;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Share your password for your Account with anyone;</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Use the Websites or Services in any manner that violates any applicable laws or regulations or is prohibited by these Terms; and/or</li>
        <li className={classNames(css.subtitle, css['is-6'])}>Assist or permit any persons in engaging in any of the activities described in this listing.</li>
      </ul>
      <p className={classNames(css.subtitle, css['is-6'])}>While using the Website or Materials, you agree to comply with these and all Standards, as well as all applicable laws, rules and regulations. Topixin has the sole discretion to delete, suspend, terminate or close your Account, with or without prior notification to you, for any violation of the Terms, including any of the Standards.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>8. Charges and Billing (Does not apply to Free Plan).</p>
      <p className={classNames(css.subtitle, css['is-6'])}>When and if you opt in for a premium plan, you agree to pay all fees or charges incurred by your Account, including applicable taxes at the time that the applicable fee or charge becomes payable. Unless otherwise indicated, all prices are in US Dollars. Topixin may add new products and services for additional fees and charges, or proactively amend fees and charges for Services and/or Materials, at any time in our sole discretion. You represent to Topixin that you are an authorized user of the chosen method of payment used to pay any fees you incur plus all applicable taxes. YOU ACKNOWLEDGE AND AGREE THAT YOU ARE FULLY LIABLE FOR ALL FEES AND CHARGES MADE THROUGH YOUR ACCOUNT.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>9. Third Party Sites/Services.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The Websites may include links to other websites or services (including advertisements and payment providers) solely as a convenience to you ("Linked Sites"). The inclusion of any Linked Site does not imply endorsement by Topixin of any third party, third party websites or any association with the operators of such Linked Sites. You are responsible for viewing and abiding by the privacy statements and terms of service/use posted at any third party or Linked Sites. The information, products, materials and services on Linked Sites is not under the control of Topixin and Topixin does not provide or endorse any such Linked Sites or the information, products, materials or services contained on or available or accessible on or through any Linked Sites. Topixin responsible if any Linked Site is not functioning properly. Topixin makes no express or implied warranties with regard to the information, products, materials or services that are contained on or accessible through any Linked Sites. Access and use of any Linked Sites, including the information, products, materials and services on any Linked Sites or available through any Linked Sites, is solely at your own risk, and you acknowledge and agree that Topixin is not responsible or liable, directly or indirectly, for any loss or damage caused or alleged to be caused by your use of any or dealings with any Linked Site or as the result of the presence of any advertisers on the Websites or available through any Third Party Platforms. Your correspondence or business dealings with, or participation in promotions of any advertisers found on or through the Websites, including in or through the Services, are solely between you and such advertiser. Any dealings with third parties, such as advertisers, included within the Websites or available on or through any Third Party Platform or participation in Promotions (defined below) involving the delivery of and payment for goods and services, or any other terms, conditions, warranties, or representations associated with such third parties, are solely between you and that third party. Topixin is neither responsible nor liable for any part of such dealings with any third parties, including any Promotions.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>When using Topixin for discovering and publishing YouTube content, you expressively agree with the YouTube Terms of Service.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>10. Forums & Submissions.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The Services may include features such as ratings, message boards, e-mail services, blogs and/or other forums or areas where you and others can post or transmit information onto or through the Websites or Services, including through Third Party Platforms (collectively, the "Forums"), and Topixin may redistribute content you send/upload/post to the Websites or through Third Party Platforms. By sending, posting or transmitting to Topixin, including photos, graphics, creative suggestions, ideas or User Ideas, notes, concepts, information, ratings or other materials (collectively, "Submissions") or by posting such Submissions to any area of the Websites (including without limitation, the Forums) or on Third Party Platforms, you grant Topixin and our designees and users a worldwide, non-exclusive, sublicensable (through multiple tiers), assignable, royalty-free, perpetual, irrevocable right to use, reproduce, distribute (through multiple tiers), create derivative works of, publicly perform, publicly display, digitally perform, make, have made, sell, offer for sale and import such Submissions in any media now known or hereafter developed, for any purpose whatsoever, commercial or otherwise, without compensation to you or the provider of the Submissions. None of the Submissions will be subject to any obligation, whether of confidentiality, attribution or otherwise, on our part and we will not be liable for any use or disclosure of any Submissions. Information and Submissions contained on our Forums may be provided by persons not affiliated with us. You agree not to transmit any Submission to or through the Websites, Services or Third Party Platforms, or to Topixin that you consider to be confidential or proprietary, and any and all Submissions shall be deemed non-confidential. You are responsible and liable for any Submissions.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You acknowledge and agree that your communications with other users via the Forums are public and not private communications, and that you have no expectation of privacy concerning your use of the Forums. You acknowledge that personal information that you communicate via the Forums may be seen and used by others and result in unsolicited communications; therefore, Topixin strongly encourages you not to disclose any personal information about yourself in your communications via the Forums. Topixin is not responsible for information that you choose to communicate to other users via the Forums or Submission.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You acknowledge that a large volume of information is available in our Forums and that people participating in such Forums occasionally post Submissions or make statements, whether intentionally or unintentionally, that are inaccurate, misleading, illegal or deceptive. We neither endorse nor are responsible for such Submissions or statements, or for any opinion, advice, information or other utterance made or displayed on the Websites or Services, through Third Party Platforms, or in any Forums by third persons or parties. The opinions expressed in the Forums reflect solely the opinion(s) of the participants of the Forums and do not necessarily reflect the opinion(s) of Topixin. Topixin is not responsible for any errors or omissions in articles or postings, for hyperlinks embedded in any Submissions or for any results obtained from the use of any such statements or information. Under no circumstances will Topixin or our affiliates, suppliers or agents be liable for any loss or damage caused by your reliance on the Submissions or on any information or materials obtained through the Websites, Services, or any Third Party Platform. Topixin has no obligation to monitor the Websites, Services, any Third Party Platform, or the Forums, or any Submissions or other materials that you or other third persons or parties transmit or post on the Websites, in the Services, on any Third Party Platform, or in the Forums. You acknowledge and agree that Topixin has the right (but not the obligation) to do any or all of the following, at its sole discretion: (i) alter, remove, or refuse to post or allow to be posted or stored any Submission or message; (ii) monitor and/or filter any of your communications through the Forums (including without limitation, by means of blocking or replacing expletives or other language that may be deemed harmful or offensive); and/or (iii) disclose any Submission or message or any communication through the Forums, and the circumstances surrounding the transmission thereof, to any third party in order to operate the Websites or any Services available thereon or through any Third Party Platform to (a) protect Topixin and its sponsors, employees, officers, directors, shareholders, agents, representatives and affiliates, and Topixin's users and visitors; (b) to comply with legal obligations or governmental requests; and (c) to enforce these Terms; or for any other reason or purpose.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Notwithstanding anything contrary stated in these Terms, by posting a Submission you represent and warrant that (a) you own or otherwise control all of the rights including without limitation, all copyrights, to your Submission or are otherwise legally entitled to post the submission; (b) the content is accurate; (b) use of the content you supply does not violate the Terms and will not cause injury to any person or entity; and (d) you will indemnify Topixin and/or its subsidiaries and affiliates for all claims resulting from any content, information, and ratings, including without limitation, all Submissions, you supply, provide or transmit to Topixin or the Websites or any Third Party Platform. Topixin has the right, but not the obligation, to monitor and edit or remove any activity or content. Topixin takes no responsibility and assumes no liability for any content, materials or Submissions posted by you or any third party. TOPIXIN RESERVES THE RIGHT TO REMOVE ANY SUBMISSIONS THAT IT DETERMINES IN ITS SOLE DISCRETION VIOLATES ANY LAW OR RIGHT OF ANY PERSON, INFRINGES THE RIGHTS OF ANY PERSON, OR IS OTHERWISE INAPPROPRIATE FOR POSTING ON THE WEBSITES, IN OR THROUGH USE OF THE SERVICES, OR ON OR THROUGH ANY THIRD PARTY PLATFORM.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>11. Right to Modify.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Topixin reserves the right, at any time, to modify, suspend, or discontinue the Websites, the Materials, including the Services, and/or any part or parts thereof with or without notice. You agree that Topixin will not be liable to you or to any third party for any such modification, suspension, or discontinuation.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>12. Acknowledgements.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You hereby agree and acknowledge that : (a) Topixin has the right to obtain without notification to you certain information about your computer or software, including without limitation, your operating system, identification of your hard drives, central processing unit, MAC address, IP address, and Internet browser for purposes of identification and other lawful purposes; (b) Topixin has the right to obtain without notification to you non-personal information from your connection to the Websites, Services or through any Third Party Platform for demographic or any other lawful purposes; and (c) TOPIXIN has the right to obtain without notification to you information from your computer, software, and parts or portions thereof, including without limitation, your computer's random access memory, video card, central processing unit, hard drive(s) and any other storage devices in order to assist our efforts in policing users who may develop and/or use "hacks." The information obtained in this Section may be used for the purpose of identifying persons or entities not in compliance or believed by Topixin to not be in compliance with the Terms and any and all other Topixin Standards, rules, policies, notices and/or agreements.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You acknowledge and agree that you (and not Topixin) are responsible for obtaining and maintaining all telecommunications, broadband, and computer hardware, equipment, and services needed to access and use any service provided by Topixin, including without limitation, the Websites, Services, or any Third Party Platforms, and paying all charges related thereto. You also acknowledge that you are responsible for obtaining and maintaining your access to any website through which you access Topixin's products or Services, including the Websites and any Third Party Platforms.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>13. Claims of Copyright Infringement.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The Digital Millennium Copyright Act of 1998 (the "DMCA") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that materials hosted by Topixin infringe your copyright (for example, materials posted by a user on one of our Forums), you (or your agent) may send us a notice requesting that the material be removed or access to it blocked. Please see the requirements and specific instructions for submitting a notice to Topixin on Topixin's DMCA Policy. If you believe in good faith that a notice of copyright infringement has been wrongly filed against you, the DMCA permits you to send Topixin a counter-notice. Please refer to Topixin's DMCA Policy for the requirements and instructions for submitting a counter-notice. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA; see http://www.copyright.gov for details. Notices and counter-notices with respect to the Websites, including the Services, should be sent to Topixin's DMCA Agent for notice of claims of copyright infringement.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Topixin's DMCA Agent should be contacted only for the purposes set forth in this Section 12. ALL OTHER INQUIRIES DIRECTED TO Topixin's DMCA AGENT WILL NOT BE ANSWERED.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>14. Use & Access.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>YOU MUST BE AT LEAST 13 YEARS OF AGE TO (a) USE THE WEBSITES OR THE SERVICES, (b) USE ANYTHING ACCESSIBLE OR AVAILABLE ON OR THROUGH THE WEBSITES OR THROUGH THIRD PARTY PLATFORMS, (c) CREATE AN ACCOUNT, OR (d) TRANSMIT/SUBMIT/POST ANY SUBMISSION, ANY PERSONAL INFORMATION OR ANYTHING TO ANY FORUM OR ANYWHERE ELSE ON THE WEBSITES. By accessing, using and/or submitting information to or through any of the Websites or Services, including Services available on or through Third Party Platforms, you represent that you are at least 13 years of age or older and otherwise have the legal capacity to enter into these Terms.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Pursuant to 47 U.S.C. Section 230(d), as amended, we hereby notify you that parental control protections (such as computer hardware, software or filtering services) are commercially available that may assist you in limiting access to material that is harmful to minors. Information identifying current providers of protections is available from America Links Up: http://www.netparents.org/parentstips/browsers.html.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>AGES 13-18: IF YOU ARE A PARENT OR GUARDIAN AND YOU PROVIDE YOUR CONSENT TO YOUR TEENAGER'S REGISTRATION WITH THE WEBSITES AND/OR THE SERVICES, YOU AGREE TO BE BOUND BY THESE TERMS IN RESPECT OF SUCH TEENAGER'S USE OF THE WEBSITES, THE SERVICES AND/OR ANYTHING ACCESSIBLE OR AVAILABLE ON OR THROUGH THE WEBSITES OR THIRD PARTY PLATFORMS.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>15. Privacy/Security.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You understand that any information provided by you or collected by us in connection with your use of the Websites or the Services will be used in the manner described in these Terms of Use and in our Privacy Policy, which, as stated above, is incorporated into these Terms of Use and collectively from the Terms. If you do not agree to the terms of the Privacy Policy you may not use the Websites or Services, including any Services available on or through Third Party Platforms. Without limiting the terms of the Privacy Policy, you understand that we do not guarantee that your use of the Websites or Services, including any Services available on or through any Third Party Platforms, and/or the information provided by you will be private or secure, and we are not responsible or liable to you for any lack of privacy or security you may experience. You are fully responsible for taking precautions and providing security measures best suited for your situation and intended use of the Websites or the Services, including any Services available on or through any Third Party Platform.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>16. Sweepstakes/Contests.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>From time to time we may offer or allow you to participate in promotions, giveaways, contests or sweepstakes (each, a "Promotion") on our Websites, through the Services, or through a Third Party Platform. Participation in any Promotion is subject to the Official Rules governing that Promotion. Topixin may announce rules in connection with any Promotion, but regardless of whether specific rules are announced, all such opportunities will be controlled by the Terms, unless specifically superseded by Promotion-specific rules. If you choose to participate in a Promotion, we may collect your personal information, such as your name, address, age, telephone number, email address or other contact information. In addition, as a condition to receiving any awards or prizes for participating in such Promotions, you may be required to provide additional information, to sign a release, or to authorize the use of certain biographical or other information about you in Topixin's marketing materials. Please also be aware that if a third party administers the Promotion, your participation may be subject to additional terms and conditions, and you should specifically read such third party's rules, terms of service, and privacy policies before participating. You agree that Topixin is not responsible for such third parties' promotions.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>17. Jurisdictional Issues.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Access to and use of the Websites and Materials, including any Services, from any jurisdiction where the content, products or services is illegal is strictly prohibited. Topixin makes no representation that Materials, including any Services, available on or through the Websites or Third Party Platforms are appropriate or available for use in any jurisdictions outside the United States and those who choose to access or use any of the Websites or Materials, including any Services, from such other jurisdictions do so on their own initiative and at their own risk, and are responsible for compliance with local laws, rules or regulations, including, without limitation, rules about the internet, data, e-mail, or privacy.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>18. Export Control.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Any software available on or through the Websites or through the Services is subject to United States export controls. No software may be downloaded or otherwise exported or re-exported: (a) into (or to a national or resident of) Cuba, Iraq, Libya, North Korea, Iran, Syria or any other country to which the U.S. has embargoed goods or which is subject to other applicable U.S. trade sanctions; or (b) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Commerce Department's Table of Deny Orders. By downloading or using any such software, you represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list. You further agree to comply with all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside, regardless of whether such transmission is permitted under the Terms or by applicable law.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>19. User Ideas.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Topixin may accept or consider unsolicited ideas, including ideas for new promotions, products, applications, technologies, processes or other ideas or inventions (collectively, "User Ideas"). You must not transmit any User Ideas to or through the Websites, Services, or Third Party Platforms, or to Topixin that you consider to be confidential or proprietary. You agree that any and all User Ideas are non-confidential and non-proprietary and will and need not be treated as such. You are responsible and liable for any User Ideas. You agree that by submitting User Ideas to Topixin, including any concepts, know-how or ideas, you hereby grant Topixin a perpetual, worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of and display the User Ideas in connection with the Website and Topixin's (and its successor's) business, including without limitation, for promoting and redistributing part or all of the User Ideas (and derivative works thereof) in any media formats and through any media channels whether now known or hereafter developed, without payment or accounting to you or others. Topixin is not obligated to review, evaluate, publish, or use any User Idea.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>20. Termination.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Your right to access and use the Websites and Materials, including the Services, will remain effective until terminated in accordance with the Terms. Topixin reserves the right to revoke the limited license granted to you herein for any reason or no reason, and, if we do, Topixin may terminate your access to and use of the Websites and Materials, including the Services, and may, in its sole discretion maintain or delete your Account, including without limitation, any topics/topic names. If Topixin revokes your license, you agree that Topixin will not have any liability to you for any time spent by you accessing or using the Websites or the Services, and/or Submissions associated with your Account, or for any other reason whatsoever. For example, you understand that value cannot and shall not be attributed to the time that you may spend creating topics, creating Submissions and/or or accumulating or creating any other digital and/or virtual objects, and you understand and agree that you will not be compensated under any circumstances for any topics or Submissions, regardless of whether you are barred from access to them.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Topixin may suspend, terminate, modify, or delete your Account with or without notice to you, at any time for any reason or for no reason, including without limitation, for violation or suspected violation of the Terms. For example, your Account may be deleted and terminated without warning if Topixin believes, in its sole discretion, that you are under 13 years of age; if you provide any information that is untrue, inaccurate (or becomes untrue, inaccurate, not current or incomplete); or Topixin has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete. Upon termination, your right to access and use the Websites and Materials, including the Services, will immediately cease. In addition to its termination rights, Topixin also reserves the right to refuse service to anyone and to remove content, Submissions or Materials for any reason whatsoever in its sole discretion.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You may terminate your Account online here. Topixin may terminate and delete your Account, including any topics associated with your Account, in our sole discretion, if your Account and/or any topics have been inactive for a period of at least 3 months. Your Account will be considered inactive if you do not log on to any Websites or Services using your username and password and your topic will be considered inactive if you do not add to or modify it.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The provisions of Sections 2, 4 through 8, 10, 12, 15, 19, 20 through 24, 28, 29, 31 and 32 will survive any termination of the Terms.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>21. Disclaimers.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>THE WEBSITES AND THE MATERIALS, INCLUDING WITHOUT LIMITATION ANY PRODUCTS OR SERVICES OBTAINED ON OR AVAILABLE THROUGH THE WEBSITES OR ANY THIRD PARTY PLATFORM, ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, TOPIXIN AND ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS AND AGENTS, DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, ACCURACY, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE. TOPIXIN AND ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS AND AGENTS DO NOT WARRANT THAT YOUR USE OF THE WEBSITES OR THE MATERIALS, INCLUDING WITHOUT LIMITATION ANY PRODUCTS OR SERVICES AVAILABLE ON OR THROUGH THE WEBSITES OR ANY THIRD PARTY PLATFORM, WILL BE UNINTERRUPTED, ERROR-FREE OR SECURE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE WEBSITES OR THE MATERIALS (OR ANY PART THEREOF INCLUDING THE SERVICES), THE SUBMISSIONS, THE SERVER(S) ON WHICH THE WEBSITES OR SERVICES ARE HOSTED, OR ANY PRODUCTS OR SERVICES AVAILABLE ON THE WEBSITES OR ON OR THROUGH ANY THIRD PARTY PLATFORM ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. NO OPINION, ADVICE OR STATEMENT OF TOPIXIN OR ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS, AGENTS, MEMBERS OR VISITORS, WHETHER MADE ON THE WEBSITES, IN THE MATERIALS, ON THIRD PARTY PLATFORMS OR OTHERWISE, SHALL CREATE ANY WARRANTY. YOUR USE OF THE WEBSITES AND MATERIALS, INCLUDING WITHOUT LIMITATION ANY PRODUCTS AND SERVICES PROVIDED ON OR THROUGH THE WEBSITES OR ANY THIRD PARTY PLATFORM, ARE ENTIRELY AT YOUR OWN RISK.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>22. Inaccuracies.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>A possibility exists that the Websites and Materials, including the Services, and any Services available on or through any Third Party Platform, could include inaccuracies or errors, or information or materials that violate the Terms. Additionally, a possibility exists that unauthorized alterations could be made by third parties to the Websites or Materials, including any Services, and any Services available on or through any Third Party Platform. Although Topixin attempts to ensure the integrity of the Websites and Materials, including the Services, and any Services available on or through any Third Party Platform, we make no guarantees as to any Website's or Material's completeness or correctness. In the event that a situation arises in which a Website's or Material's completeness or correctness is in question, please contact us at support@topixin.com (with the subject line "Inaccuracies in Websites or on Third Party Platforms") with, if possible, a description of the material to be checked and the location (URL) where such material can be found on the Website or Third Party Platform at issue, as well as information sufficient to enable us to contact you. We will try to address your concerns as soon as reasonably practicable. For copyright infringement claims, see the Section on "Claims of Copyright Infringement" above.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>23. Limitation of Liability.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>NEITHER TOPIXIN NOR ANY OF OUR SUBSIDIARIES, AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS OR SPONSORS, NOR OUR OR THEIR DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, AGENTS OR OTHER REPRESENTATIVES, ARE RESPONSIBLE OR LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE OR OTHER DAMAGES (INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS, LOSS OF DATA OR LOST PROFITS), UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY WAY TO THE WEBSITES AND/OR MATERIALS, INCLUDING ANY MATERIALS AVAILABLE THROUGH ANY THIRD PARTY PLATFORM, SUBMISSIONS, ANY LINKED WEBSITES OR ANY CODE, PRODUCT OR SERVICE PURCHASED, ACCESSIBLE OR USABLE THROUGH THE WEBSITES OR ANY THIRD PARTY PLATFORM. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE WEBSITES, MATERIALS, INCLUDING ANY PRODUCTS OR SERVICES AVAILABLE ON THE WEBSITES OR THROUGH ANY THIRD PARTY PLATFORM, SUBMISSIONS OR ANY LINKED WEBSITES IS TO STOP USING THE WEBSITES, MATERIALS, SUBMISSIONS, PRODUCTS, SERVICES, OR LINKED WEBSITES, AS APPLICABLE. THE SOLE AND EXCLUSIVE MAXIMUM LIABILITY TO TOPIXIN FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING WITHOUT LIMITATION, NEGLIGENCE) OR OTHERWISE, SHALL BE THE TOTAL AMOUNT PAID BY YOU TO TOPIXIN IN THE PRECEDING TWELVE (12) MONTHS, IF ANY, TO ACCESS OR USE THE WEBSITES OR SERVICES. YOU AGREE THAT THE DAMAGE EXCLUSIONS IN THESE TERMS OF USE SHALL APPLY EVEN IF ANY REMEDY FAILS OF ITS ESSENTIAL PURPOSE. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. NO COMMUNICATION OF ANY KIND BETWEEN YOU AND TOPIXIN OR A REPRESENTATIVE OF TOPIXIN CONSTITUTES A WAIVER OF ANY LIMITATIONS OF LIABILITY HEREUNDER OR CREATE ANY ADDITIONAL WARRANTY NOT EXPRESSLY STATED IN THE TERMS. MULTIPLE CLAIMS WILL NOT INCREASE THE MONETARY DAMAGES LIMIT STATED HEREIN.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>24. Indemnification.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>You agree to indemnify, defend and hold harmless Topixin, our affiliates, licensors, suppliers, advertisers and sponsors, and our and their directors, officers, employees, consultants, agents and other representatives, from and against any and all claims, damages, losses, costs (including without limitation, reasonable attorneys' fees and expenses) and other expenses that arise directly or indirectly out of or from: (a) any allegation that any Submission or other information you post, submit to us or transmit to the Websites or through a Third Party Platform infringes or otherwise violates the copyright, trademark, trade secret or other intellectual property or other right of any third party; (b) your breach or violation (including through use of your username, topic name, or Account, whether or not by you) of the Terms, including the Standards, or any applicable laws or regulations; (c) your access to and use of the Websites, the Materials, including any Services, and including any Services available on or through any Third Party Platform, or Submissions; (d) any viruses, spyware, or other similar harmful or intrusive program code posted, submitted or transmitted by you to the Websites, in the Services, or on any Third Party Platform; and/or (e) any claim that one of your postings, User Ideas or Submissions caused damage to a third party, including without limitation, libel, defamation, loss of or harm to reputation or any other damage whatsoever.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>25. Questions.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The Website is provided by Topixin Inc. If you have any questions, comments or complaints regarding the Terms, the Websites or the Materials, please feel free to contact us at: contact@Topixin (with the subject line "Questions, Comments or Complaints").</p>
      <p className={classNames(css.subtitle, css['is-4'])}>26. Notice for California Users</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Under California Civil Code Section 1789.3, California website users are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 400 R Street, Suite 1080, Sacramento, California 95814, or by telephone at (916) 445-1254 or (800) 952-5210.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>27. System Outages.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Topixin periodically schedules system downtime for the Websites and Services for maintenance and other purposes. Additionally, unplanned system outages may occur. You agree that Topixin has no responsibility and is not liable for: (a) the unavailability of the Websites or Materials, including the Services, and including the Services available on or through any Third Party Platform; (b) any loss of materials, data, transactions or any other information or materials caused by such system outages; (c) the resultant delay, mis-delivery, or non-delivery of data, transactions or any other information or materials caused by such system outages; or (d) any outages caused by any third parties, including without limitation, any companies or servers hosting the Websites or Materials, any Internet service provides, or any Internet facilities and networks.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>28. Statute of Limitations.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>Any claim or cause of action arising out of or related to use of the Websites, the Materials, including any Services, and including any Services available on or through any Third Party Platform, or the Terms (including the Terms of Use and/or Privacy Policy) must be filed within 1 year after such claim or cause or action arose regardless of any statutes or law to the contrary. In the event any such claim or cause of action is not filed within such 1 year period, such claim or cause of action are forever barred.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>29. Choice of Law/Venue.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The Terms are governed by and construed in accordance with the laws of the State of California, United States of America, without regards to its principles of conflicts of law that would require the application of the laws of another jurisdiction. Any disputes between you and Topixin relating to the Websites, the Materials, including the Services, and including the Services available on or through any Third Party Platform, that involve a claim of less than $5,000 must be resolved exclusively through binding non-appearance-based arbitration. A party electing arbitration shall initiate proceedings by filing an arbitration demand with the American Arbitration Association (AAA). The arbitration proceedings shall be governed by the AAA Commercial Arbitration Rules, Consumer Due Process Protocol, and Supplementary Procedures for Resolution of Consumer-Related Disputes. In addition, you and Topixin agree that the following rules shall apply to the arbitration proceedings: (a) the arbitration shall be conducted, at the option of the party seeking relief, by telephone, online, or based solely on written submissions; (b) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties; and (c) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Any disputes between you and Topixin that involve a claim of more than $5,000 are subject to the exclusive jurisdiction of the Federal and State courts located in San Francisco, California.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>30. Mobile Terms.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>The Websites and Materials, including Services available on or through Third Party Platforms, may include versions designed for mobile content that may be viewed on mobile devices (the "Mobile Site").  In order to use the Mobile Site, you must have a wireless mobile device capable of two-way messaging and wireless service through a participating mobile service provider. You agree that are solely responsible for all charges that you incur from your mobile service provider for your use of the Mobile Site. All charges are billed by and payable to your mobile service provider. Please contact your mobile service provider for pricing plans and details.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>31. Notices.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>All notices required or permitted to be given under this Agreement must be in writing and shall be given by personal delivery, registered or certified mail, or Federal Express or other nationally recognized courier service which regularly tracks its packages, if to Topixin to its Registered Agent with the State of California, and if to you, to the e-mail and/or postal address associated with your Account. Notices, if personally delivered, shall be deemed to have been received on the date of delivery; if by registered or certified mail, on the third business day after mailing; if by Federal Express or e-mail, on the second business day after deposit with the service. You may not send any notices under this Section to Topixin via e-mail.</p>
      <p className={classNames(css.subtitle, css['is-4'])}>32. Miscellaneous.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>If any provision of the Terms is found to be unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from the Terms and shall not affect the validity and enforceability of any remaining provisions. This is the entire agreement between you and Topixin relating to the subject matter herein and supersedes any and all prior or contemporaneous written or oral agreements between us with respect to such subject matter. The Terms are not assignable, transferable or sublicensable by you except with Topixin's prior written consent. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by the Terms. Any heading, caption or section title contained herein is inserted only as a matter of convenience and in no way defines or explains any section or provision hereof. Topixin's performance of the Terms is subject to existing laws and legal process, and nothing contained in the Terms is in derogation of Topixin's right to comply with governmental, court, and law enforcement requests or requirements relating to your access and/or use of the Websites or the Materials, including the Services, and including the Services available on or through any Third Party Platform, or information provided to or gathered by Topixin with respect to such access and/or use. A printed version of the Terms and of any notices given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to the Terms to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. The parties agree that all correspondence relating to these Terms of Use, must be written in the English language.</p>
      <p className={classNames(css.subtitle, css['is-6'])}>© 2020 Topixin Inc. -- All Rights Reserved. Updated: June 29, 2020</p>
    </div>
  );
};

export default TermsPage;
